/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEduTrustCredential,
  IEduTrustCredentialInterface,
} from "../../../contracts/X402PaymentVerifier.sol/IEduTrustCredential";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getCredential",
    outputs: [
      {
        internalType: "string",
        name: "title",
        type: "string",
      },
      {
        internalType: "string",
        name: "issuer",
        type: "string",
      },
      {
        internalType: "string",
        name: "ipfsHash",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "issuedAt",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "revoked",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEduTrustCredential__factory {
  static readonly abi = _abi;
  static createInterface(): IEduTrustCredentialInterface {
    return new Interface(_abi) as IEduTrustCredentialInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEduTrustCredential {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IEduTrustCredential;
  }
}
