/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as x402PaymentVerifierSol from "./X402PaymentVerifier.sol";
export type { x402PaymentVerifierSol };
export type { EduTrustCredential } from "./EduTrustCredential";
