/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NotesMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "MAX_PRICE"
      | "MIN_PRICE"
      | "MIN_WITHDRAWAL"
      | "activeListingIds"
      | "buyNote"
      | "delistNote"
      | "earnings"
      | "feeRecipient"
      | "getActiveListings"
      | "getActiveListingsCount"
      | "getEarnings"
      | "getListing"
      | "getTotalTransactions"
      | "getTransaction"
      | "getUserTransactions"
      | "listNote"
      | "listings"
      | "notesContract"
      | "owner"
      | "platformFeePercent"
      | "renounceOwnership"
      | "royaltyContract"
      | "setFeeRecipient"
      | "setNotesContract"
      | "setPlatformFee"
      | "transactions"
      | "transferOwnership"
      | "userTransactions"
      | "withdrawEarnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EarningsWithdrawn"
      | "NoteDelisted"
      | "NoteListed"
      | "NoteSold"
      | "OwnershipTransferred"
      | "PlatformFeeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_PRICE", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_WITHDRAWAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeListingIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delistNote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "earnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveListings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveListingsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTransactions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listNote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "notesContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNotesContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTransactions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_PRICE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WITHDRAWAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeListingIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyNote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delistNote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "earnings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveListingsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listNote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "notesContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNotesContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NoteDelistedEvent {
  export type InputTuple = [tokenId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [tokenId: bigint, seller: string];
  export interface OutputObject {
    tokenId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NoteListedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    seller: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, seller: string, price: bigint];
  export interface OutputObject {
    tokenId: bigint;
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NoteSoldEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    seller: AddressLike,
    buyer: AddressLike,
    price: BigNumberish,
    platformFee: BigNumberish,
    royaltyPaid: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    seller: string,
    buyer: string,
    price: bigint,
    platformFee: bigint,
    royaltyPaid: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    seller: string;
    buyer: string;
    price: bigint;
    platformFee: bigint;
    royaltyPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NotesMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): NotesMarketplace;
  waitForDeployment(): Promise<this>;

  interface: NotesMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE: TypedContractMethod<[], [bigint], "view">;

  MIN_WITHDRAWAL: TypedContractMethod<[], [bigint], "view">;

  activeListingIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  buyNote: TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;

  delistNote: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  earnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getActiveListings: TypedContractMethod<[], [bigint[]], "view">;

  getActiveListingsCount: TypedContractMethod<[], [bigint], "view">;

  getEarnings: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getListing: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        seller: string;
        price: bigint;
        listedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getTotalTransactions: TypedContractMethod<[], [bigint], "view">;

  getTransaction: TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        tokenId: bigint;
        seller: string;
        buyer: string;
        price: bigint;
        platformFee: bigint;
        royaltyPaid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getUserTransactions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  listNote: TypedContractMethod<
    [tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        seller: string;
        price: bigint;
        listedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  notesContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  royaltyContract: TypedContractMethod<[], [string], "view">;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setNotesContract: TypedContractMethod<
    [newContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        tokenId: bigint;
        seller: string;
        buyer: string;
        price: bigint;
        platformFee: bigint;
        royaltyPaid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userTransactions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawEarnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WITHDRAWAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeListingIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyNote"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "delistNote"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "earnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveListings"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getActiveListingsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEarnings"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        seller: string;
        price: bigint;
        listedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        tokenId: bigint;
        seller: string;
        buyer: string;
        price: bigint;
        platformFee: bigint;
        royaltyPaid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTransactions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "listNote"
  ): TypedContractMethod<
    [tokenId: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        seller: string;
        price: bigint;
        listedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "notesContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "royaltyContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNotesContract"
  ): TypedContractMethod<[newContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint] & {
        tokenId: bigint;
        seller: string;
        buyer: string;
        price: bigint;
        platformFee: bigint;
        royaltyPaid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userTransactions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "NoteDelisted"
  ): TypedContractEvent<
    NoteDelistedEvent.InputTuple,
    NoteDelistedEvent.OutputTuple,
    NoteDelistedEvent.OutputObject
  >;
  getEvent(
    key: "NoteListed"
  ): TypedContractEvent<
    NoteListedEvent.InputTuple,
    NoteListedEvent.OutputTuple,
    NoteListedEvent.OutputObject
  >;
  getEvent(
    key: "NoteSold"
  ): TypedContractEvent<
    NoteSoldEvent.InputTuple,
    NoteSoldEvent.OutputTuple,
    NoteSoldEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    "EarningsWithdrawn(address,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "NoteDelisted(uint256,address)": TypedContractEvent<
      NoteDelistedEvent.InputTuple,
      NoteDelistedEvent.OutputTuple,
      NoteDelistedEvent.OutputObject
    >;
    NoteDelisted: TypedContractEvent<
      NoteDelistedEvent.InputTuple,
      NoteDelistedEvent.OutputTuple,
      NoteDelistedEvent.OutputObject
    >;

    "NoteListed(uint256,address,uint256)": TypedContractEvent<
      NoteListedEvent.InputTuple,
      NoteListedEvent.OutputTuple,
      NoteListedEvent.OutputObject
    >;
    NoteListed: TypedContractEvent<
      NoteListedEvent.InputTuple,
      NoteListedEvent.OutputTuple,
      NoteListedEvent.OutputObject
    >;

    "NoteSold(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      NoteSoldEvent.InputTuple,
      NoteSoldEvent.OutputTuple,
      NoteSoldEvent.OutputObject
    >;
    NoteSold: TypedContractEvent<
      NoteSoldEvent.InputTuple,
      NoteSoldEvent.OutputTuple,
      NoteSoldEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
