/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEduTrustCredential } from "./IEduTrustCredential";
export type { X402PaymentVerifier } from "./X402PaymentVerifier";
