/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace X402PaymentVerifier {
  export type VerificationRecordStruct = {
    verifier: AddressLike;
    tokenId: BigNumberish;
    paidAmount: BigNumberish;
    timestamp: BigNumberish;
    accessHash: BytesLike;
  };

  export type VerificationRecordStructOutput = [
    verifier: string,
    tokenId: bigint,
    paidAmount: bigint,
    timestamp: bigint,
    accessHash: string
  ] & {
    verifier: string;
    tokenId: bigint;
    paidAmount: bigint;
    timestamp: bigint;
    accessHash: string;
  };
}

export interface X402PaymentVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PROTOCOL_SHARE"
      | "STUDENT_SHARE"
      | "accessDuration"
      | "accessGrants"
      | "credentialContract"
      | "feeRecipient"
      | "getAccessExpiry"
      | "getVerificationHistory"
      | "hasAccess"
      | "owner"
      | "renounceOwnership"
      | "requestVerification"
      | "setAccessDuration"
      | "setCredentialContract"
      | "setFeeRecipient"
      | "setVerificationFee"
      | "studentEarnings"
      | "transferOwnership"
      | "verificationCount"
      | "verificationFee"
      | "verificationHistory"
      | "withdrawEarnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "EarningsWithdrawn"
      | "FeeUpdated"
      | "OwnershipTransferred"
      | "VerificationPaymentReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PROTOCOL_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STUDENT_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accessDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accessGrants",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessExpiry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestVerification",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAccessDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCredentialContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verificationHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PROTOCOL_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STUDENT_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accessDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accessGrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAccessDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCredentialContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    verifier: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    verifier: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    verifier: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [student: AddressLike, amount: BigNumberish];
  export type OutputTuple = [student: string, amount: bigint];
  export interface OutputObject {
    student: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationPaymentReceivedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    verifier: AddressLike,
    student: AddressLike,
    amount: BigNumberish,
    accessHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    verifier: string,
    student: string,
    amount: bigint,
    accessHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    verifier: string;
    student: string;
    amount: bigint;
    accessHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402PaymentVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): X402PaymentVerifier;
  waitForDeployment(): Promise<this>;

  interface: X402PaymentVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PROTOCOL_SHARE: TypedContractMethod<[], [bigint], "view">;

  STUDENT_SHARE: TypedContractMethod<[], [bigint], "view">;

  accessDuration: TypedContractMethod<[], [bigint], "view">;

  accessGrants: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  credentialContract: TypedContractMethod<[], [string], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getAccessExpiry: TypedContractMethod<
    [verifier: AddressLike, tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getVerificationHistory: TypedContractMethod<
    [tokenId: BigNumberish],
    [X402PaymentVerifier.VerificationRecordStructOutput[]],
    "view"
  >;

  hasAccess: TypedContractMethod<
    [verifier: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestVerification: TypedContractMethod<
    [tokenId: BigNumberish, studentAddress: AddressLike],
    [string],
    "payable"
  >;

  setAccessDuration: TypedContractMethod<
    [newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCredentialContract: TypedContractMethod<
    [newContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerificationFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  studentEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  verificationFee: TypedContractMethod<[], [bigint], "view">;

  verificationHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        verifier: string;
        tokenId: bigint;
        paidAmount: bigint;
        timestamp: bigint;
        accessHash: string;
      }
    ],
    "view"
  >;

  withdrawEarnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PROTOCOL_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STUDENT_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accessDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accessGrants"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "credentialContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAccessExpiry"
  ): TypedContractMethod<
    [verifier: AddressLike, tokenId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerificationHistory"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [X402PaymentVerifier.VerificationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [verifier: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestVerification"
  ): TypedContractMethod<
    [tokenId: BigNumberish, studentAddress: AddressLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setAccessDuration"
  ): TypedContractMethod<[newDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCredentialContract"
  ): TypedContractMethod<[newContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "studentEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verificationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verificationHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        verifier: string;
        tokenId: bigint;
        paidAmount: bigint;
        timestamp: bigint;
        accessHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VerificationPaymentReceived"
  ): TypedContractEvent<
    VerificationPaymentReceivedEvent.InputTuple,
    VerificationPaymentReceivedEvent.OutputTuple,
    VerificationPaymentReceivedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,address,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "EarningsWithdrawn(address,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VerificationPaymentReceived(uint256,address,address,uint256,bytes32)": TypedContractEvent<
      VerificationPaymentReceivedEvent.InputTuple,
      VerificationPaymentReceivedEvent.OutputTuple,
      VerificationPaymentReceivedEvent.OutputObject
    >;
    VerificationPaymentReceived: TypedContractEvent<
      VerificationPaymentReceivedEvent.InputTuple,
      VerificationPaymentReceivedEvent.OutputTuple,
      VerificationPaymentReceivedEvent.OutputObject
    >;
  };
}
